import type { Policy } from './types';
import { AGE_BANDS } from './types';

/** 전 연령대 허용 */
const ALL = AGE_BANDS;
/** 만 34세 이하 (버팀목·주택드림·청년수당 등) */
const U34 = ['19-23', '24-29', '30-34'] as const;

/**
 * 정책 데이터 (구현안내서 9절 스키마).
 *
 * 원본 8분야 → 4계열 매핑은 구현안내서 8절을 따른다.
 *   주거   ← ① 주거·이사
 *   일자리 ← ③ 취창업 + ④ 교육
 *   금융   ← ② 금융·자산 + ⑤ 생활지원
 *   심리   ← ⑥ 마음·건강 + ⑦ 문화·예술 + ⑧ 기타
 *
 * 소득 조건은 부스에서 확인할 수 없으므로 필터에 쓰지 않고
 * target 에 그대로 적어 참여자가 스스로 확인하게 한다. (7절)
 */
export const POLICIES: Policy[] = [
  // ───────────────── 주거 ─────────────────
  {
    id: 'HS01',
    applicationWindow: { start: '2026-05-06', end: '2026-05-19' },
    checkedAt: '2026-09-07',
    sourceUrl: 'https://www.seoul.go.kr/news/news_notice.do?nttNo=457234&tr_code=snews',
    series: '주거',
    title: '서울시 청년월세 지원',
    target: '서울 거주 19~39세 무주택 청년. 1인가구·신혼부부·한부모 등 신청 유형별 소득·주택 기준 확인',
    support: '월 최대 20만원 × 최대 12개월 (총 최대 240만원)',
    period: '2026.5.6 ~ 5.19 18:00',
    reason: '매달 나가는 월세가 부담되는 청년에게',
    url: 'https://housing.seoul.go.kr',
    direction: '현금',
    ages: [...ALL],
    situations: null,
  },
  {
    id: 'HS02',
    series: '주거',
    title: '청년 임차보증금 이자지원',
    target: '19~39세 청년, 소득 기준 충족, 서울시 내 주택 임차 예정자',
    support: '임차보증금 대출 최대 2억원 및 대출이자 일부 지원',
    period: '상시 / 대출 신청 시',
    reason: '전세보증금 마련과 이자가 부담되는 청년에게',
    url: 'https://housing.seoul.go.kr/site/main/content/sh01_040901',
    direction: '주거',
    ages: [...ALL],
    situations: null,
  },
  {
    id: 'HS03',
    applicationWindow: { start: '2026-08-18', end: '2026-08-31' },
    checkedAt: '2026-09-07',
    sourceUrl: 'https://housing.seoul.go.kr/site/main/tvReportedInfo/list?cp=3',
    series: '주거',
    title: '청년 부동산 중개보수 및 이사비 지원',
    target: '19~39세, 서울로 전입하거나 서울 내 이사한 청년, 소득 기준 등',
    support: '부동산 중개보수 및 이사비 최대 40만원 실비 지원',
    period: '상반기 4.1~4.14 / 하반기 8.18~8.31',
    reason: '취업·독립 때문에 이사하며 비용이 부담되는 청년에게',
    url: 'https://youth.seoul.go.kr/youthConts.do?key=2310100044',
    direction: '현금',
    ages: [...ALL],
    situations: null,
  },
  {
    id: 'HS04',
    series: '주거',
    title: '청년전용 버팀목전세자금',
    target: '만 34세 이하 무주택 청년 세대주 등 요건 충족',
    support: '전세자금 마련을 위한 저금리 전세자금 대출',
    period: '연중 / 대출 신청 시',
    reason: '목돈이 부족해 전세로 독립하기 어려운 청년에게',
    url: 'https://nhuf.molit.go.kr',
    direction: '주거',
    ages: [...U34],
    situations: null,
  },
  {
    id: 'HS05',
    series: '주거',
    title: '청년전용 보증부 월세대출',
    target: '만 34세 이하 무주택 청년 세대주 등 요건 충족',
    support: '보증금 및 월세금 저금리 대출 지원',
    period: '연중 / 대출 신청 시',
    reason: '월세와 보증금이 모두 부담되는 독립 초기 청년에게',
    url: 'https://nhuf.molit.go.kr',
    direction: '주거',
    ages: [...U34],
    situations: null,
  },
  {
    id: 'HS06',
    series: '주거',
    title: '청년 주택드림 청약통장',
    target: '만 34세 이하 무주택 청년, 소득 등 요건 충족',
    support: '높은 금리 혜택 및 청약·자산형성 지원',
    period: '상시 / 가입 가능 시',
    reason: '앞으로 내 집 마련을 준비하고 싶은 청년에게',
    url: 'https://nhuf.molit.go.kr',
    direction: '주거',
    ages: [...U34],
    situations: null,
  },

  // ───────────────── 일자리 (취창업 + 교육) ─────────────────
  {
    id: 'JB01',
    series: '일자리',
    title: '서울 청년수당',
    target: '서울 거주 만 19~34세 미취업 청년, 중위소득 150% 이하 등',
    support: '월 50만원 × 최대 6개월 활동지원금',
    period: '연 1~2회 모집 (공고 확인)',
    reason: '구직 활동 중 생활비가 막막한 청년에게',
    url: 'https://youth.seoul.go.kr',
    direction: '현금',
    ages: [...U34],
    situations: ['취업준비생', '휴식'],
  },
  {
    id: 'JB02',
    series: '일자리',
    title: '청년취업사관학교 (SeSAC)',
    target: '서울 거주 청년, 디지털 직무 전환 희망자',
    support: '무료 실무 교육 + 취업 연계',
    period: '기수별 모집',
    reason: '직무 역량을 새로 쌓아 취업을 준비하고 싶은 청년에게',
    url: 'https://sesac.seoul.kr',
    direction: '성장',
    ages: [...ALL],
    situations: ['학생', '취업준비생', '휴식'],
  },
  {
    id: 'JB03',
    series: '일자리',
    title: '취업날개 서비스',
    target: '서울 거주 만 19~39세 미취업 청년',
    support: '면접 정장 무료 대여 (연 최대 10회)',
    period: '상시',
    reason: '면접을 앞두고 준비 비용이 부담되는 청년에게',
    url: 'https://youthjob.seoul.go.kr',
    direction: '성장',
    ages: [...ALL],
    situations: ['학생', '취업준비생'],
  },
  {
    id: 'JB04',
    series: '일자리',
    title: '국민내일배움카드',
    target: '구직자 및 재직자 (일부 제외 대상 있음)',
    support: '직업훈련비 최대 300~500만원 지원',
    period: '상시',
    reason: '자격증·직업훈련으로 다시 시작하고 싶은 청년에게',
    url: 'https://www.hrd.go.kr',
    direction: '성장',
    ages: [...ALL],
    situations: null,
  },
  {
    id: 'JB05',
    series: '일자리',
    title: '청년일자리도약장려금',
    target: '취업애로청년을 정규직 채용한 기업 및 해당 청년',
    support: '장기근속 인센티브 및 기업 지원금',
    period: '연중 (예산 소진 시 마감)',
    reason: '정규직으로 안착하고 싶은 청년에게',
    url: 'https://www.work.go.kr',
    direction: '현금',
    ages: [...ALL],
    situations: ['취업준비생', '직장인'],
  },
  {
    id: 'JB06',
    series: '일자리',
    title: '청년도전지원사업',
    target: '구직단념청년 등 만 18~34세',
    support: '맞춤형 프로그램 + 참여수당·이수 인센티브',
    period: '기관별 모집',
    reason: '오래 쉬어 다시 시작할 자신이 없는 청년에게',
    url: 'https://www.work.go.kr',
    direction: '성장',
    ages: [...U34],
    situations: ['취업준비생', '휴식'],
  },
  {
    id: 'JB07',
    series: '일자리',
    title: '국가기술자격 응시료 지원',
    target: '만 34세 이하 청년',
    support: '국가기술자격 응시료 50% 지원 (연 3회)',
    period: '상시',
    reason: '자격증 준비 비용을 아끼고 싶은 청년에게',
    url: 'https://www.q-net.or.kr',
    direction: '성장',
    ages: [...U34],
    situations: null,
  },
  {
    id: 'JB08',
    series: '일자리',
    title: 'K-Move 스쿨 (해외취업지원)',
    target: '만 34세 이하 해외취업 희망 청년',
    support: '해외취업 연수 과정 및 취업 알선',
    period: '과정별 모집',
    reason: '해외로 커리어를 넓혀보고 싶은 청년에게',
    url: 'https://www.worldjob.or.kr',
    direction: '성장',
    ages: [...U34],
    situations: ['학생', '취업준비생'],
  },

  // ───────────────── 금융 (금융·자산 + 생활지원) ─────────────────
  {
    id: 'FN01',
    series: '금융',
    title: '서울시 희망두배 청년통장',
    target: '서울 거주 만 18~34세 근로 청년, 소득·부양의무자 기준 충족',
    support: '월 15만원 저축 + 동일액 매칭 → 최대 1,080만원 + 이자',
    period: '정기 모집',
    reason: '월급을 받아도 저축이 잘 안 되는 청년에게',
    url: 'https://account.welfare.seoul.kr',
    direction: '현금',
    ages: [...U34],
    situations: ['직장인', '프리랜서'],
  },
  {
    id: 'FN02',
    series: '금융',
    title: '서울 영테크',
    target: '서울시 거주 19~39세 청년',
    support: '전문가 1:1 재무상담 및 자산관리 교육 무료 제공',
    period: '상시',
    reason: '돈 관리를 어디서부터 해야 할지 모르겠는 청년에게',
    url: 'https://youth.seoul.go.kr',
    direction: '성장',
    ages: [...ALL],
    situations: null,
  },
  {
    id: 'FN03',
    applicationWindow: { start: '2026-08-03', end: '2026-09-15' },
    checkedAt: '2026-09-07',
    sourceUrl: 'https://youth.seoul.go.kr/bbs/list.do?key=2303300002',
    series: '금융',
    title: '학자금대출 이자 지원',
    target: '서울 거주 대학생·대학원생 등 학자금대출 이용자',
    support: '학자금대출 이자 전액 또는 일부 지원',
    period: '2026년 2차: 8.3 ~ 9.15 (마감 시각은 공고 확인)',
    reason: '학자금대출 이자가 부담되는 청년에게',
    url: 'https://youth.seoul.go.kr',
    direction: '현금',
    ages: [...ALL],
    situations: ['학생', '취업준비생'],
  },
  {
    id: 'FN04',
    series: '금융',
    title: '청년미래적금',
    target: '만 19~34세 근로 청년, 소득 요건 충족',
    support: '정부 기여금 + 비과세 혜택으로 목돈 마련',
    period: '가입 기간별 공고',
    reason: '목돈을 만들고 싶은 근로 청년에게',
    url: 'https://www.fsc.go.kr',
    direction: '현금',
    ages: [...U34],
    situations: ['직장인', '프리랜서'],
  },
  {
    id: 'FN05',
    series: '금융',
    title: '청년 기후동행카드',
    target: '만 19~39세 서울 대중교통 이용 청년',
    support: '월 정액 무제한 대중교통 + 청년 할인',
    period: '상시',
    reason: '매달 교통비가 아까운 청년에게',
    url: 'https://news.seoul.go.kr/traffic',
    direction: '현금',
    ages: [...ALL],
    situations: null,
  },
  {
    id: 'FN06',
    series: '금융',
    title: '서울형 입원 생활비 지원',
    target: '서울 거주 근로자·자영업자, 소득·재산 기준 충족',
    support: '입원·검진 기간 생활임금 기준 일급 지원',
    period: '상시 (퇴원일 기준 신청기한 있음)',
    reason: '아파서 일을 쉬면 수입이 끊기는 청년에게',
    url: 'https://health.seoul.go.kr',
    direction: '현금',
    ages: [...ALL],
    situations: ['직장인', '프리랜서'],
  },
  {
    id: 'FN07',
    series: '금융',
    title: '디딤돌소득',
    target: '저소득 가구, 소득·재산 등 기준 충족',
    support: '소득이 적을수록 더 많이 지원하는 소득보장 정책',
    period: '사업별 공고 확인',
    reason: '소득이 적어 생활 자체가 버거운 청년에게',
    url: 'https://seoulsafetyincome.welfare.seoul.kr',
    direction: '현금',
    ages: [...ALL],
    situations: null,
  },

  // ───────────────── 심리 (마음·건강 + 문화·예술 + 기타) ─────────────────
  {
    id: 'MN01',
    series: '심리',
    title: '청년 마음건강 지원사업',
    target: '서울 거주 만 19~39세 청년',
    support: '전문 심리상담 무료 제공 (기본 4회 ~ 최대 10회)',
    period: '분기별 모집',
    reason: '번아웃과 스트레스로 지쳐 있는 청년에게',
    url: 'https://youth.seoul.go.kr',
    direction: '마음',
    ages: [...ALL],
    situations: null,
  },
  {
    id: 'MN02',
    series: '심리',
    title: '고립은둔청년 지원사업',
    target: '사회적 고립을 경험 중인 만 19~39세 청년',
    support: '일상회복 프로그램, 관계 형성 활동, 사례관리',
    period: '상시 (기관별 확인)',
    reason: '사람 만나는 일이 부담스러워진 청년에게',
    url: 'https://youth.seoul.go.kr',
    direction: '마음',
    ages: [...ALL],
    situations: ['휴식', '취업준비생'],
  },
  {
    id: 'MN03',
    series: '심리',
    title: '서울 청년센터 (오랑)',
    target: '서울 거주·활동 청년 누구나',
    support: '진로·생활 상담, 공간 이용, 커뮤니티 프로그램',
    period: '상시',
    reason: '어디에 물어봐야 할지 모르겠는 청년에게',
    url: 'https://youth.seoul.go.kr',
    direction: '마음',
    ages: [...ALL],
    situations: null,
  },
  {
    id: 'MN04',
    checkedAt: '2026-09-07',
    sourceUrl: 'https://youthculturepass.or.kr/',
    eligibilityNote: '19~23세 구간 전체 대상이 아니에요. 2026년에는 2006~2007년생만 해당하며, 지역별 추가 발급 여부를 확인해야 해요.',
    series: '심리',
    title: '청년문화예술패스',
    target: '대한민국 국적의 2006~2007년생 (2026년 19~20세). 기존 이용·발급 이력 등 제외 조건 확인',
    support: '공연·전시·영화·도서 이용 지원 (수도권 연 15만원, 비수도권 20만원)',
    period: '지역별 추가 발급 공지 확인 (예산 소진 시 마감)',
    reason: '문화생활을 하고 싶지만 비용이 부담되는 청년에게',
    url: 'https://www.arko.or.kr/content/6033',
    direction: '마음',
    ages: ['19-23'],
    situations: null,
  },
  {
    id: 'MN05',
    series: '심리',
    title: '예술창작활동 지원',
    target: '서울에서 작품 제작·발표를 진행하는 청년 예술인(단체)',
    support: '작품 제작 및 발표 창작활동비 지원',
    period: '공모별 상이',
    reason: '창작을 이어가고 싶지만 창작비가 부족한 청년에게',
    url: 'https://www.scas.kr/scas',
    direction: '성장',
    ages: [...ALL],
    situations: ['프리랜서', '휴식'],
  },
  {
    id: 'MN06',
    series: '심리',
    title: '서울노동권익센터',
    target: '취약 노동자 및 서울 시민',
    support: '노동권 상담, 권리구제 및 복지지원',
    period: '상시',
    reason: '임금체불·부당대우 등 노동 문제가 생긴 청년에게',
    url: 'https://www.labors.or.kr',
    direction: '마음',
    ages: [...ALL],
    situations: ['직장인', '프리랜서'],
  },
  {
    id: 'MN07',
    series: '심리',
    title: '무료법률구조지원',
    target: '경제적 어려움 등 일정 요건을 충족하는 대상자',
    support: '법률상담 및 소송 등 법률구조 지원',
    period: '상시 / 요건별 상이',
    reason: '법적인 문제가 생겼지만 변호사 비용이 부담되는 청년에게',
    url: 'https://www.klac.or.kr',
    direction: '마음',
    ages: [...ALL],
    situations: null,
  },
];
